#:schema https://github.com/joshmedeski/sesh/raw/main/sesh.schema.json

[[session]]
name = "dev"
path = "~/ukon"
startup_command = "~/.config/sesh/scripts/two-windows.sh"

[[session]]
name = "mystuff"
path = "~/mystuff"
startup_command = "~/.config/sesh/scripts/two-windows.sh"

[[session]]
name = "ukon-core"
path = "~/ukon/ukon-core"
startup_command = "~/.config/sesh/scripts/edit-code.sh"

[[session]]
name = "ui"
path = "~/ukon/ui"
startup_command = "~/.config/sesh/scripts/edit-code.sh"
