#:schema https://github.com/joshmedeski/sesh/raw/main/sesh.schema.json

[[session]]
name = "dev"
path = "~/ukon/active"
startup_command = "~/.config/sesh/scripts/work.sh"

[[session]]
name = "ukon-core"
path = "~/ukon/active/ukon-core"
startup_command = "~/.config/sesh/scripts/two-windows.sh"

[[session]]
name = "ui"
path = "~/ukon/active/ui"
startup_command = "~/.config/sesh/scripts/two-windows.sh"
