theme = "catppuccin_mocha"

[editor]
line-number = "absolute"
cursorline = true
color-modes = true
bufferline = "multiple"
true-color = true
scrolloff = 8
idle-timeout = 250
auto-format = true
completion-trigger-len = 3
text-width = 100
rulers = [100]
end-of-line-diagnostics = "hint"
# to use system clipboard by default
# default-yank-register = "+"
[editor.statusline]
left = [
    "mode",
    "spinner",
    "file-name",
    "read-only-indicator",
    "file-modification-indicator",
]
center = []
right = [
    "diagnostics",
    "selections",
    "register",
    "position",
    "file-encoding",
    "file-line-ending",
    "file-type",
]

[editor.lsp]
display-inlay-hints = true
display-messages = true
auto-signature-help = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
#git-ignore = false

[editor.indent-guides]
render = true
character = "│"

[editor.soft-wrap]
enable = true
wrap-at-text-width = false

[editor.whitespace.render]
nbsp = "all"
tab = "all"

[keys.normal]
C-s = ":w"
# S-h = ":buffer-previous"
# S-l = ":buffer-next"
esc = ["collapse_selection", "keep_primary_selection"]
K = "hover"
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-k = [
    "extend_to_line_bounds",
    "delete_selection",
    "move_line_up",
    "paste_before",
]
C-e = "scroll_down"
C-y = "scroll_up"

[keys.select]
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-k = [
    "extend_to_line_bounds",
    "delete_selection",
    "move_line_up",
    "paste_before",
]
">" = ["indent", "collapse_selection"]
"<" = ["unindent", "collapse_selection"]

[keys.normal.g]
o = "flip_selections"
[keys.select.g]
o = "flip_selections"
